vim.api.nvim_create_user_command("Update", function()
	require("lazy").update()
	require("lazy").clean()
	vim.cmd("TSUpdate all")
end, {})

vim.api.nvim_create_user_command("Config", function()
	vim.cmd.edit("$MYVIMRC")
	vim.cmd.cd("%:p:h")
end, {})
