return {
	diagnostics = {
		Error = " ",
		Warn = " ",
		Hint = " ",
		Info = " ",
	},
	buffer = {
		modified = "",
		readonly = "󰌾",
		unnamed = "",
		newfile = "󰝒",
	},
	git = {
		LineAdded = " ",
		LineModified = " ",
		LineRemoved = " ",
		FileDeleted = "",
		FileIgnored = "◌",
		FileRenamed = "",
		FileStaged = "S",
		FileUnmerged = "",
		FileUnstaged = "",
		FileUntracked = "U",
		Diff = "",
		Repo = "",
		Octoface = "",
		Branch = "",
	},
	kind_icons = {
		Array = "",
		Boolean = "",
		Key = "",
		Namespace = "",
		Null = "󰟢",
		Number = "",
		Object = "",
		Package = "",
		Reference = "",
		Snippet = "",
		String = "",
		Text = "",
		TypeParameter = "",
		Unit = "",
		Method = "󰆧",
		Function = "󰡱",
		Constructor = "",
		Field = "󰜢",
		Variable = "",
		Class = "󰠱",
		Interface = "",
		Module = "",
		Property = "󰜢",
		Value = "󰎠",
		Enum = "",
		Keyword = "󰌋",
		Color = "󰏘",
		File = "󰈙",
		Folder = "󰉋",
		EnumMember = "",
		Constant = "󰏿",
		Struct = "󰙅",
		Event = "",
		Operator = "󰆕",
	},
}
