return {
	diagnostics = {
		Error = "X",
		Warn = "!",
		Hint = "?",
		Info = "i",
	},
	buffer = {
		Modified = "M",
		Readonly = "R",
		Unnamed = "U",
		Newfile = "N",
	},
	git = {
		LineAdded = "+",
		LineModified = "~",
		LineRemoved = "-",
		FileDeleted = "x",
		FileIgnored = "=",
		FileRenamed = "r",
		FileModified = "m",
		FileStaged = "s",
		FileUnmerged = "󱈖 ",
		FileUnstaged = "󱧃 ",
		FileUntracked = "󰡯 ",
		FileConflict = "󰩋 ",
		Diff = "",
		Repo = "",
		Octoface = "",
		Branch = "",
	},
	lazy = {
		cmd = "[CMD]",
		config = "[CFG]",
		event = "[EVT]",
		favorite = "[FAV]",
		ft = "[FT]",
		init = "[INIT]",
		import = "[IMPT]",
		keys = "[KEY]",
		lazy = "[LZY]",
		loaded = "+",
		not_loaded = "-",
		plugin = "[PLG]",
		runtime = "[RUNT]",
		require = "[REQ]",
		source = "[SRC]",
		start = "[SRT]",
		task = "[TSK]",
		list = {
			"+",
			"~",
			"*",
			"-",
		},
	},
	kinds = {
		Array = "ARR",
		Boolean = "BOOL",
		Key = "KEY",
		Namespace = "NS",
		Null = "NULL",
		Number = "NUM",
		Object = "OBJ",
		Package = "PKG",
		Reference = "RGR",
		Snippet = "SNIP",
		String = "STR",
		Text = "TXT",
		TypeParameter = "TYPE",
		Unit = "UNIT",
		Method = "MTHD",
		Function = "FUNC",
		Constructor = "CON",
		Field = "FIELD",
		Variable = "VAR",
		Class = "CLASS",
		Interface = "INTF",
		Module = "MOD",
		Property = "PROP",
		File = "FILE",
		Folder = "DIR",
		Value = "VAL",
		Enum = "ENUM",
		Keyword = "KEYW",
		Color = "CLR",
		EnumMember = "ENUMM",
		Constant = "CONST",
		Struct = "STRCT",
		Event = "EVNT",
		Operator = "OPS",
	},
}
